### ISSUE TITLE
DA file request

### ISSUE THREAD

**Issue by Jambul46** [arzam16/empty-sixty-five#1]
would it be possible for you to provide the MT6589 DA file?

**Comment by arzam16** [comment]
@Jambul46 sure: https://gofile.io/d/HQynYz
The link contains the extracted mt6589 download agent and the original DA it was carved out from.
The individual DAs are generated by simply running the `make` command and I'm quite surprised you asked for a reupload. Is there something wrong with the code? Do you get an error maybe? Please let me know if there's something in the code I could fix.

**Comment by Jambul46** [comment]
Iam asking only because this is the only page/git mentioning MT6589 DA and i need it to reflash my tablet. For some reason iam getting error "Fail to download DA to baseband chip's internal sram" (tried multiple MTK_all_in_one but non of them worked) so i wanned to try it with DA specifically meant for this SoC

**Comment by Jambul46** [comment]
Also thanks for providing me with the files

**Comment by arzam16** [comment]
@Jambul46 Whatever software you are using to flash your tablet (I assume it's SP Flash Tool), it won't work with the carved-out mt6589 DA I provided. The reason is the flashing software expects a more complete file with its own headers and extra data while the carved-out DA is *just* a chunk of executable pure machine code. It won't work at all. On the other side, the MTK_AllInOne_DA.bin should work since it has necessary headers.

"Fail to download DA to baseband chip's internal sram" is an interesting error that requires reading logs for further understanding. This repository is for mt65xx research and unfortunately I can't provide support for your problem right here. You can reach me out on Matrix (my contact is in my github profile) on that matter but I don't guarantee I can find a working solution for you.

**Comment by Jambul46** [comment]
Yup figured that out the hard way. Also what is Matrix never heard of it (besides the movie).
